server:
  port: 8080
  servlet:
    context-path: /bpm


#mysql
default:
  url: jdbc:mysql://127.0.0.1:3306/bpm?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
  username: root
  password: 123456

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: false
  common:
    app:
      #     目前先设置一个正确但是不一定可用的url地址
      idm-url: http://localhost:8080/flowable-idm1
      idm-admin:
        #       需要设置一个密码，目前先设置，后期不使用
        password: test
        #       默认user为admin，这个地方可设置可不设置
        user: admin1
mybatis:
  type-aliases-package: cn.gzsendi
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true